export const NavLinksList = {
	LINK_EN: [
		{ name: 'Feature', url: '#feature' },
		{ name: 'Testimonial', url: '#testimonial' },
		{ name: 'About', url: '/about' },
		{ name: 'Privacy', url: '/privacy' },
		{ name: 'Terms', url: '/terms' },
	],

	LINK_ZH: [
		{ name: '功能', url: '#feature' },
		{ name: '评价', url: '#testimonial' },
		{ name: '关于', url: '/about' },
		{ name: '隐私', url: '/privacy' },
		{ name: '条款', url: '/terms' },
	],
	LINK_ES: [
		{ name: 'Característica', url: '#feature' },
		{ name: 'Precios', url: '#pricing' },
		{ name: 'Testimonio', url: '#testimonial' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'Acerca de', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
	LINK_RU: [
		{ name: 'Функция', url: '#feature' },
		{ name: 'оценивать', url: '#testimonial' },
		{ name: 'о', url: '/about' },
		{ name: 'конфиденциальность', url: '/privacy' },
		{ name: 'Условия', url: '/terms' },
	],
	LINK_JA: [
		{ name: '特徴', url: '#feature' },
		{ name: '価格', url: '#pricing' },
		{ name: 'お客様の声', url: '#testimonial' },
		{ name: 'よくある質問', url: '#faq' },
		{ name: 'アバウト', url: '/about' },
		{ name: 'ブログ', url: '/blog' },
	],
	LINK_AR: [
		{ name: 'ميزة', url: '#feature' },
		{ name: 'التسعير', url: '#pricing' },
		{ name: 'شهادة', url: '#testimonial' },
		{ name: 'الأسئلة الشائعة', url: '#faq' },
		{ name: 'حول', url: '/about' },
		{ name: 'مدونة', url: '/blog' },
	],
	LINK_FR: [
		{ name: 'Fonctionnalités', url: '#feature' },
		{ name: 'Tarification', url: '#pricing' },
		{ name: 'Témoignages', url: '#testimonial' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'À propos', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
};
